### ISSUE TITLE
0.9.3: Selling Big Poe at Curiosity shop crashes the game

### ISSUE THREAD

**Issue by Ammako** [RecompRando/MMRecompRando#109]
What the title says.

<details>
  <summary>yaml, but maybe only shopsanity off is relevant? idk</summary>

```
# Q. What is this file?
# A. This file contains options which allow you to configure your multiworld experience while allowing
#    others to play how they want as well.
#
# Q. How do I use it?
# A. The options in this file are weighted. This means the higher number you assign to a value, the
#    more chances you have for that option to be chosen. For example, an option like this:
#
#    map_shuffle:
#      on: 5
#      off: 15
#
#    Means you have 5 chances for map shuffle to occur, and 15 chances for map shuffle to be turned
#    off.
#
# Q. I've never seen a file like this before. What characters am I allowed to use?
# A. This is a .yaml file. You are allowed to use most characters.
#    To test if your yaml is valid or not, you can use this website:
#        http://www.yamllint.com/
#    You can also verify that your Archipelago options are valid at this site:
#        https://archipelago.gg/check

# Your name in-game, limited to 16 characters.
#     {player} will be replaced with the player's slot number.
#     {PLAYER} will be replaced with the player's slot number, if that slot number is greater than 1.
#     {number} will be replaced with the counter value of the name.
#     {NUMBER} will be replaced with the counter value of the name, if the counter value is greater than 1.
name: Ammako

# Used to describe your yaml. Useful if you have multiple files.
description: Default Majora's Mask Recompiled Template

game: Majora's Mask Recompiled
requires:
  version: 0.6.1 # Version of Archipelago required for this yaml to work as expected.

Majora's Mask Recompiled:
  # Game Options
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # 
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0 # equivalent to 0
    normal: 50 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # 
    # **Full:** ensure everything can be reached and acquired.
    # 
    # **Minimal:** ensure what is needed to reach your goal can be acquired.
    full: 50
    minimal: 0

  logic_difficulty:
    # Set the logic difficulty used when generating.
    normal: 50
    no_logic: 0

  majora_remains_required:
    # Set the amount of boss remains required to fight Majora.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 4
    4: 50
    random: 0
    random-low: 0
    random-high: 0

  moon_remains_required:
    # Set the amount of boss remains required to reach the Moon after playing Oath to Order.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 4
    4: 50
    random: 0
    random-low: 0
    random-high: 0

  camc:
    # Set whether chest appearance matches contents.
    'false': 50
    'true': 0

  swordless:
    # Start the game without a sword, and shuffle an extra Progressive Sword into the pool.
    'false': 50
    'true': 0

  shieldless:
    # Start the game without a shield, and shuffle an extra Progressive Shield into the pool.
    'false': 50
    'true': 0

  start_with_soaring:
    # Start the game with Song of Soaring.
    'false': 0
    'true': 50

  starting_hearts:
    # The number of heart quarters Link starts with.
    # If less than 12, extra heart items will be shuffled into the pool to accommodate.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 4
    # Maximum value is 12
    12: 50
    random: 0
    random-low: 0
    random-high: 0

  starting_hearts_are_containers_or_pieces:
    # Choose whether Link's starting hearts are shuffled into the pool as Heart Containers (plus the remainder as Heart Pieces) or as all Heart Pieces.
    containers: 50
    pieces: 0

  shuffle_regional_maps:
    # Choose whether to shuffle every regional map from Tingle.
    vanilla: 0
    starting: 50
    anywhere: 0

  shuffle_boss_remains:
    # Choose whether to shuffle the Boss Remains received after beating a boss at the end of a dungeon.
    # 
    # vanilla: Boss Remains are placed in their vanilla locations.
    # anything: Any item can be given by any of the Boss Remains, and Boss Remains can be found anywhere in any world.
    # bosses: Boss Remains are shuffled amongst themselves as the rewards for defeating bosses.
    vanilla: 0
    anywhere: 50
    bosses: 0

  remains_allow_boss_warps:
    # Choose whether to retain the vanilla ability to warp the boss of dungeons by having their vanilla remains.
    # Getting the remains check for a dungeon will open its warp regardless.
    'false': 0
    'true': 50

  shuffle_spiderhouse_reward:
    # Choose whether to shuffle the Mask of Truth given at the end of the Southern Spider House and the Wallet Upgrade at the end of the Ocean Spider House.
    'false': 0
    'true': 50

  skullsanity:
    # Choose what items gold skulltulas can give.
    # 
    # vanilla: Keep the swamphouse in generation, but only place Skulltula tokens there.
    # anything: Any item can be given by any Skulltula, and tokens can be found anywhere in any world.
    # ignore: Remove the swamphouse from generation entirely, lowering the hint percentage.
    vanilla: 0
    anything: 50
    ignore: 0

  shopsanity:
    # Choose whether shops and their items are shuffled into the pool.
    # This includes Trading Post, Bomb Shop, Goron Shop, and Zora Shop, along with the Gorman Ranch and Milk Bar purchases.
    # 
    # vanilla: Shop items are not shuffled.
    # enabled: Every item in shops are shuffled, with alternate shops sharing the same items.
    # advanced: Every single item in shops are shuffled, including the alternate Night Trading Post and Spring Goron Shop.
    vanilla: 50
    enabled: 0
    advanced: 0

  scrubsanity:
    # Choose whether to shuffle Business Scrub purchases.
    'false': 50
    'true': 0

  shop_prices:
    # Choose how expensive shop items are.
    # These only apply to the main shops of the game.
    # This has no effect if shopsanity is disabled.
    # 
    # vanilla: Shop items have their normal prices.
    # free: All shop items are free and cost 0 Rupees.
    # cheap: Shop items vary in price but can all be purchased with the starting wallet.
    # expensive: Shop items vary in price but may require the Adult's Wallet. No shop items will require the Giant's Wallet.
    # offensive: Shop items vary in price but may require the Adult's Wallet and sometimes even the Giant's Wallet.
    vanilla: 50
    free: 0
    cheap: 0
    expensive: 0
    offensive: 0

  cowsanity:
    # Choose whether to shuffle Cows.
    'false': 50
    'true': 0

  shuffle_great_fairy_rewards:
    # Choose whether to shuffle Great Fairy rewards.
    'false': 0
    'true': 50

  keysanity:
    # Choose whether Small Keys are shuffled into the pool.
    'false': 0
    'true': 50

  fairysanity:
    # Choose whether Stray Fairies are shuffled into the pool.
    'false': 0
    'true': 50

  start_with_consumables:
    # Choose whether to start with basic consumables (99 rupees, 10 deku sticks, 20 deku nuts).
    'false': 50
    'true': 0

  permanent_chateau_romani:
    # Choose whether the Chateau Romani stays even after a reset.
    'false': 50
    'true': 0

  start_with_inverted_time:
    # Choose whether time starts out inverted at Day 1, even after a reset.
    'false': 50
    'true': 0

  receive_filled_wallets:
    # Choose whether you receive wallets pre-filled (not including the starting wallet).
    'false': 50
    'true': 0

  magic_is_a_trap:
    # Set whether to preserve the vanilla bug where you are able to use certain magic items and abilities without magic.
    # Once you receive magic, those items and abilities will begin to reduce magic normally.
    # 
    # (No logical implications)
    'false': 50
    'true': 0

  damage_multiplier:
    # Adjust the amount of damage taken.
    half: 0
    normal: 50
    double: 0
    quad: 0
    ohko: 0

  death_behavior:
    # Change what happens when you die.
    # 
    # vanilla: The normal death cutscene plays when you die.
    # fast: The death cutscene is massively sped up.
    # moon_crash: Triggers a moon crash and restarts the current cycle.
    vanilla: 50
    fast: 0
    instant: 0
    moon_crash: 0

  death_link:
    # When you die, everyone who enabled death link dies. Of course, the reverse is true too.
    'false': 50
    'true': 0

  link_tunic_color:
    # Choose a color for Link's tunic.
    [30, 105, 27]

  # Item & Location Options
  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_inventory:
    # Start with these items.
    {}

  start_inventory_from_pool:
    # Start with these items and don't place them in the world.
    # 
    # The game decides what the replacement items will be.
    Dungeon Map (Woodfall): 1
    Dungeon Map (Snowhead): 1
    Dungeon Map (Great Bay): 1
    Dungeon Map (Stone Tower): 1
    Compass (Woodfall): 1
    Compass (Snowhead): 1
    Compass (Great Bay): 1
    Compass (Stone Tower): 1

  start_hints:
    # Start with these item's locations prefilled into the ``!hint`` command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the ``!hint`` command.
    []

  exclude_locations:
    # Prevent these locations from having an important item.
    - West Clock Town Bank 200 Rupees
    - West Clock Town Bank 500 Rupees
    - West Clock Town Bank 1000 Rupees

  priority_locations:
    # Prevent these locations from having an unimportant item.
    []

  item_links:
    # Share part of your item pool with other players.
    []
```

</details>
